---
- name: Install the 'lmod' package
  package: name=Lmod state=present

- name: Ensure that the tcl-based 'environment-modules' package is not installed
  package: name=environment-modules  state=absent

- name: Set MODULEPATH variable.
  lineinfile:
    path: /etc/environment
    regexp: "MODULEPATH=.*"
    line: "MODULEPATH={{ lmod_module_path|join(':') }}"
    state: present
  when: lmod_module_path | length > 0

- name: force /etc/profile.d/module.sh
  ansible.builtin.copy: 
    src: module.sh
    dest: /etc/profile.d/module.sh
    mode: '0644'

- name: force /etc/profile.d/module.csh
  ansible:builtin.copy:
    src: modules.csh
    dest: /etc/profile.d/module.csh
    mode: '0644'