---
- name: Install the 'lmod' package
  ansible.builtin.package:
    name: Lmod
    state: present

- name: Set MODULEPATH variable.
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "MODULEPATH=.*"
    line: "MODULEPATH={{ lmod_module_path | join(':') }}"
    state: present
  when: lmod_module_path | length > 0

- name: Set LMOD module path as preffered alternative
  ansible.builtin.alternatives:
    name: modules.sh
    path: /usr/share/lmod/lmod/init/profile
